import { HeroSection } from "@/components/landing/hero-section";
import { PricingSection } from "@/components/landing/pricing-section";
import { StylesShowcase } from "@/components/landing/styles-showcase";
import { Button } from "@/components/ui/button";
import {
  Brain,
  Film,
  ImageIcon,
  Music,
  PenTool,
  Upload,
  Video,
  Youtube,
  Zap,
  ArrowRight,
  Ghost,
  Volume2,
} from "lucide-react";
import Link from "next/link";

const STEPS = [
  {
    number: "01",
    title: "Describe Your Vision",
    description:
      "Write an idea or paste a full script. Our AI understands narrative structure and turns your words into a cinematic blueprint.",
    icon: PenTool,
  },
  {
    number: "02",
    title: "AI Builds Your Scene",
    description:
      "Characters are cast, shots are framed, voiceovers are narrated, and music is scored — all automatically generated by AI.",
    icon: Ghost,
  },
  {
    number: "03",
    title: "Export & Share Anywhere",
    description:
      "Download your finished video or publish directly to YouTube. Multi-scene, professionally produced, ready for any platform.",
    icon: Upload,
  },
];

const FEATURES = [
  { icon: Brain, title: "AI Story Generation" },
  { icon: ImageIcon, title: "HD Visuals" },
  { icon: Volume2, title: "Professional Voiceovers" },
  { icon: Music, title: "Background Scores" },
  { icon: Film, title: "Multi-Scene Editing" },
  { icon: Youtube, title: "YouTube Publishing" },
  { icon: Zap, title: "Fast Rendering" },
  { icon: Video, title: "TikTok & Reels Ready" },
];

export default function LandingPage() {
  return (
    <>
      <HeroSection />

      {/* How It Works */}
      <section className="container py-16 md:py-24">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="font-nosifer text-2xl text-purple-300 md:text-[50px] md:leading-[50px]">
            How It Works
          </h2>
          <p className="mt-4 font-special text-base text-gray-400 md:text-lg">
            From idea to finished video in three simple steps — no editing
            skills required.
          </p>
        </div>

        <div className="mt-12 grid gap-8 md:grid-cols-3">
          {STEPS.map((step) => (
            <div
              key={step.number}
              className="group relative rounded-xl border border-purple-700/20 bg-purple-900/5 p-8 transition-all duration-300 hover:border-purple-500/40 hover:bg-purple-900/10"
            >
              <div className="absolute -left-3 -top-3 flex h-10 w-10 items-center justify-center rounded-full bg-purple-700 font-nosifer text-lg text-white md:h-12 md:w-12 md:text-xl">
                {step.number}
              </div>
              <div className="mb-5 mt-2 flex h-14 w-14 items-center justify-center rounded-xl bg-purple-900/40 text-purple-300 group-hover:bg-purple-700 group-hover:text-white">
                <step.icon className="h-7 w-7" />
              </div>
              <h3 className="mb-3 font-special text-xl font-bold text-white">
                {step.title}
              </h3>
              <p className="font-special text-sm leading-relaxed text-gray-400">
                {step.description}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* Video Showcase */}
      <section id="video-showcase" className="container py-16 md:py-24">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="font-nosifer text-2xl text-purple-300 md:text-[50px] md:leading-[50px]">
            See It In Action
          </h2>
          <p className="mt-4 font-special text-base text-gray-400 md:text-lg">
            From script to screen — watch how AI builds scenes, characters,
            shots, and music all in one platform.
          </p>
        </div>

        <div className="mx-auto mt-12 max-w-4xl">
          <div className="relative overflow-hidden rounded-xl border border-purple-700/30">
            <video
              autoPlay
              muted
              loop
              playsInline
              className="aspect-video w-full object-cover"
            >
              <source
                src="https://assets.openstory.so/videos/hero-loop.mp4"
                type="video/mp4"
              />
            </video>
            <div className="absolute inset-0 bg-gradient-to-t from-background/60 via-transparent to-transparent" />
          </div>
        </div>
      </section>

      {/* 15 Styles Showcase */}
      <StylesShowcase />

      {/* Features Grid */}
      <section className="container py-16 md:py-24">
        <div className="mx-auto max-w-3xl text-center">
          <h2 className="font-nosifer text-2xl text-purple-300 md:text-[50px] md:leading-[50px]">
            Everything You Need
          </h2>
          <p className="mt-4 font-special text-base text-gray-400 md:text-lg">
            A complete AI video production suite in one platform.
          </p>
        </div>

        <div className="mt-12 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
          {FEATURES.map((feature) => (
            <div
              key={feature.title}
              className="group flex flex-col items-center rounded-lg border border-purple-700/20 bg-purple-900/5 p-6 text-center transition-all duration-300 hover:border-purple-500/40 hover:bg-purple-900/10"
            >
              <div className="mb-3 flex h-12 w-12 items-center justify-center rounded-full bg-purple-900/40 text-purple-300 transition-colors group-hover:bg-purple-700 group-hover:text-white">
                <feature.icon className="h-6 w-6" />
              </div>
              <span className="font-special text-sm font-bold text-purple-300 group-hover:text-white">
                {feature.title}
              </span>
            </div>
          ))}
        </div>
      </section>

      {/* Pricing */}
      <PricingSection />

      {/* Final CTA */}
      <section className="container py-16 md:py-24">
        <div className="relative overflow-hidden rounded-2xl border border-purple-700/30 bg-purple-900/10 p-8 text-center md:p-16">
          <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,rgba(139,92,246,0.15),transparent_70%)]" />
          <div className="relative z-10">
            <h2 className="font-nosifer text-2xl text-purple-300 md:text-[50px] md:leading-[50px]">
              Ready to Create?
            </h2>
            <p className="mx-auto mt-4 max-w-xl font-special text-base text-gray-300 md:text-lg">
              Join creators who are turning ideas into films with AI. Start with
              1,000 free credits — no credit card required.
            </p>
            <div className="mt-8">
              <Link href="/generate">
                <Button
                  variant="default"
                  size="lg"
                  className="group px-10 py-6 font-jolly text-[24px]"
                >
                  Start Creating Free
                  <ArrowRight className="ml-2 h-6 w-6 transition-transform group-hover:translate-x-1" />
                </Button>
              </Link>
            </div>
            <p className="mt-4 font-special text-sm text-purple-400/60">
              Free to start · No credit card · Cancel anytime
            </p>
          </div>
        </div>
      </section>
    </>
  );
}
